version: 2
jobs:
  deploy:
    docker:
      - image: clojure:boot-2.7.1-alpine
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}-{{ checksum "platform.boot" }}
      - run: boot testing test-clj -x
      - run: boot pom jar push-snapshot
      - run: env BOOT_FILE=platform.boot boot browser push-snapshot
      - run: env BOOT_FILE=platform.boot boot node push-snapshot
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}-{{ checksum "platform.boot" }}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
