version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: clojure:boot-2.7.1-alpine
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

      - run:
          name: build client
          command: boot pom jar push-snapshot
      - run:
          name: build browser platform
          command: env BOOT_FILE=platform.boot boot browser push-snapshot
      - run:
          name: build node platform
          command: env BOOT_FILE=platform.boot boot node push-snapshot

      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
