version: 2
jobs:
  build:
    docker:
      - image: clojure:boot-2.8.1-alpine
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: build-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}
      - run: boot pom jar -f hyperfiddle-server.jar target
      - persist_to_workspace:
          root: .
          paths: target
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: build-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}

  publish:
    docker:
      - image: clojure:boot-2.8.1-alpine
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: publish-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}
      - run: boot push-snapshot -f target/hyperfiddle-server.jar
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: publish-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
