version: 2
jobs:
  build:
    docker:
      - image: clojure:boot-2.7.1-alpine
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

      - run:
          name: build service
          command: boot pom jar push-snapshot

      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
