version: 2
jobs:
  test-clj:
    docker:
      - image: clojure:boot-2.8.1-alpine
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: test-clj-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}
      - run: boot test-clj
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: test-clj-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}

  test-cljs-yarn:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: test-cljs-yarn-{{checksum "yarn.lock"}}
      - run: yarn install --frozen-lockfile --non-interactive --prod=true
      - persist_to_workspace:
          root: .
          paths: node_modules
      - save_cache:
          paths:
            - node_modules
          key: test-cljs-yarn-{{checksum "yarn.lock"}}

  test-cljs:
    docker:
      - image: hyperfiddle/boot-node
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: test-cljs-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}
      - run: boot test-cljs -x
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: test-cljs-{{checksum "boot.properties"}}-{{checksum "build.boot"}}-{{checksum "deps.edn"}}

  build:
    docker:
      - image: clojure:boot-2.8.1-alpine
        environment:
          BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
          BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: build-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot pom jar -f hyperfiddle.jar target
      - persist_to_workspace:
          root: .
          paths: target
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: build-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

  publish:
    docker:
      - image: clojure:boot-2.8.1-alpine
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: publish-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot push-snapshot -f target/hyperfiddle.jar
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: publish-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test-clj
      - test-cljs-yarn
      - test-cljs:
          requires:
            - test-cljs-yarn
      - build
      - publish:
          requires:
            - test-clj
            - test-cljs
            - build
          filters:
            branches:
              only: master
