version: 2
jobs:
  deploy:
    docker:
      - image: hyperfiddle/boot-node
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot testing test-clj
      - run: boot testing test-cljs -x
      - run: boot pom jar push-snapshot
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: project-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
