version: 2
jobs:
  test:
    docker:
      - image: hyperfiddle/boot-node
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: test-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot testing test-clj
      - run: boot testing test-cljs -x
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: test-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

  build:
    docker:
      - image: hyperfiddle/boot-node
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - restore_cache:
          key: build-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot pom jar -f hyperfiddle.jar target
      - persist_to_workspace:
          root: .
          paths: target
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: build-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

  publish:
    docker:
      - image: hyperfiddle/boot-node
    environment:
      BOOT_JVM_OPTIONS: "-Xms1024m -Xmx2048m"
      BOOT_WATCHERS_DISABLE: "yes"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: publish-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}
      - run: boot push-snapshot -f target/hyperfiddle.jar
      - save_cache:
          paths:
            - ~/.m2
            - ~/.boot/cache/lib
            - ~/.boot/cache/bin
          key: publish-{{checksum "boot.properties" }}-{{ checksum "build.boot" }}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build
      - publish:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
